CREATE TABLE USER_INFO (
	U_IDX	NUMBER(5)	NOT NULL,
	ID	VARCHAR2(30)	NULL,
	PWD	VARCHAR2(30)	NULL,
	PHONE	VARCHAR2(20)	NULL,
	EMAIL	VARCHAR2(30)	NULL,
	BIRTH	VARCHAR2(30)	NULL,
	LIKE	NUMBER(5)	NULL
);

CREATE TABLE FOLLOWER (
	NO	NUMBER(5)	NOT NULL,
	FROM_ID	VARCHAR2(30)	NULL,
	TO_ID	VARCHAR2(30)	NULL
);

CREATE TABLE FOLLOWING (
	NO	NUMBER(5)	NOT NULL,
	FROM_ID	VARCHAR2(30)	NULL,
	TO_ID	VARCHAR2(30)	NULL
);

CREATE TABLE FEED (
	F_IDX	NUMBER(5)	NOT NULL,
	REGDATE	VARCHAR2(30)	NULL,
	CONTENT	VARCHAR2(300)	NULL,
	U_IDX	NUMBER(5)	NOT NULL
);

CREATE TABLE COMM (
	CO_IDX	NUMBER(5)	NOT NULL,
	REGDATE	VARCHAR2(30)	NULL,
	COMM	VARCHAR2(100)	NULL,
	F_IDX	NUMBER(5)	NOT NULL
);

ALTER TABLE USER_INFO ADD CONSTRAINT PK_USER_INFO PRIMARY KEY (
	U_IDX
);

ALTER TABLE FOLLOWER ADD CONSTRAINT PK_FOLLOWER PRIMARY KEY (
	NO
);

ALTER TABLE FOLLOWING ADD CONSTRAINT PK_FOLLOWING PRIMARY KEY (
	NO
);

ALTER TABLE FEED ADD CONSTRAINT PK_FEED PRIMARY KEY (
	F_IDX
);

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	CO_IDX
);




